version: '3.8'

services:
  market-dashboard:
    build: .
    ports:
      - "5150:5150"
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    network_mode: "host"